name: footnoted
description: "FootNoted - your life's footprints on a misted world map."
publish_to: 'none'
resolution: workspace

version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  footnoted_geo: any
  footnoted_data: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
